
name: called from outside

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Print inputs
      run: echo ${{ github.event.inputs.name }}
     
