name: 'Delete rsp files'
description: 'Deletes rsp files'
inputs:
  target:
    description: 'Target directory'
    default: 'Assets'
    required: true
runs:
  using: 'composite'
  steps: 
  - id: Delete rps's
    run: |
      rm ${{inputs.target}}/smcs.rsp
      rm ${{inputs.target}}/gmcs.rsp
      rm ${{inputs.target}}/scs.rsp
    shell: bash
  
branding:
  icon: 'delete'
  color: 'green'