name: Dispatch reusable build imitation

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - UAT
          - Staging

jobs:

  prepare_job:
    uses: ./.github/workflows/reusable_with_output.yml

# reusable workflow call job can't have steps 
  execute_reusable:
    needs: [prepare_job]
    uses: ./.github/workflows/reusable_build_imitation.yml
    with:
      branch_name: ${{ needs.prepare_job.outputs.branch_name }}
      # environment: ${{ inputs.environment }}
    secrets: inherit