name: Manual workflow reusable
on:  
  workflow_call:
    inputs:
      name:
        default: 'World'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
  

jobs:
  
  prepare:
    runs-on: ubuntu-latest

    env:
      PLATFORM_TO_BUILD: iOS
      GAME_SERVER_ENVIRONMENT: ${{ github.event.inputs.name }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 

      - name: test echo
        run: echo "echo v1"

  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
