name: Manual workflow reusable
on:  
  workflow_call:
    inputs:
      name:
        default: 'World'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
  
env:
  GAME_SERVER_ENVIRONMENT: ${{ github.event.inputs.name }} # not wokring

jobs:

  prepare_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: working_dispatch

      - name: test echo
        run: echo "echo ${{ github.event.inputs.name }}"

      - name: test echo 2
        run: echo "BRANCH zz"

  greet:
    needs: prepare_job
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
