name: Manual workflow reusable
on:  
  workflow_call:
    inputs:
      name:
        default: 'World'
        required: true
        type: string
    #secrets: inherit
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
  
env:
  GAME_SERVER_ENVIRONMENT: ${{ github.event.inputs.name }} # not wokring

jobs:

  final_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
