name: Run another manual

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - UAT
          - Staging
          - Production
      build_version:
        description: 'Custom build version'
      build_number:
        description: 'Custom build number'

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: ./.github/workflows/my-action
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.envPAT }}

jobs:
  prepare_and_call_reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: test echo
        run: echo "echo v1"

      - uses: ./.github/workflows/manual_reusable
        with:
          name: ${{ inputs.environment }}
          # token: ${{ secrets.envPAT }}

  