name: Run another manual

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - UAT
          - Staging
          - Production
      build_version:
        description: 'Custom build version'
      build_number:
        description: 'Custom build number'

jobs:
  prepare_job:
    needs: echo_job
    uses: ./.github/workflows/reusable_with_output.yml

  echo_job:
    needs: prepare_job
    runs-on: ubuntu-latest
    steps:
      - name: use outputs
      run: echo ${{ needs.prepare_job.outputs.firstword }} ${{ needs.prepare_job.outputs.secondword }}

  checkout_job:
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: working_dispatch # works 

# reusable workflow call job can't have steps 
  execute_reusable:
    needs: prepare_job
    uses: ./.github/workflows/manual_reusable.yml
    with:
      name: ${{ github.event.inputs.environment }}