name: Call action

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - UAT
          - Staging

jobs:

  copy_commit_job:
    runs-on: ubuntu-latest
    name: A job to copy and commit
    steps:
      - uses: actions/checkout@v3
      - id: copy
        uses: ./.github/actions/copy-rsp
        # uses: kkostenkov/starter-workflows/copy-rsp@main
        with:
          file_name: ${{ inputs.environment }}
      - id: delete
        uses: ./.github/actions/delete-rsp
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash