name: Reusable with output

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      branch_name:
        description: "Branch to use"
        value: ${{ jobs.example_job.outputs.branch_name }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      branch_name: ${{ steps.step1.outputs.branch_name }}
    steps:
      - id: step1
        run: echo "::set-output name=branch_name::working_dispatch"