name: Build imitation reusable
on:  
  workflow_call:
    inputs:
      branch_name:
        type: string
      environment:
        default: 'UAT'
        type: string
    #secrets: inherit
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - UAT
          - Staging
          - Production
      build_version:
        description: 'Custom build version'
      build_number:
        description: 'Custom build number'

jobs:

  final_job:
    runs-on: ubuntu-latest
    env:
      PLATFORM_TO_BUILD: iOS
      GAME_SERVER_ENVIRONMENT: ${{ inputs.environment }}
      CUSTOM_BRANCH_NAME: ${{ inputs.branch_name || github.ref_name }} 
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ env.CUSTOM_BRANCH_NAME }}

    - name: Send greeting
      run: echo "input got ${{ env.GAME_SERVER_ENVIRONMENT }} ${{ env.CUSTOM_BRANCH_NAME }} "
