name: Build imitation reusable
on:  
  workflow_call:
    inputs:
      environment:
        default: 'UAT'
        required: true
        type: string
    #secrets: inherit
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - UAT
          - Staging
          - Production
      build_version:
        description: 'Custom build version'
      build_number:
        description: 'Custom build number'

jobs:

  final_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send greeting
      run: echo "input got ${{ inputs.environment }}"

# jobs:
#   build:
#     runs-on: [self-hosted, clientside-ci, app-builder, ios]

#     env:
#       PLATFORM_TO_BUILD: iOS
#       #GAME_SERVER_ENVIRONMENT: ${{ github.event.inputs.environment }}
#       GAME_SERVER_ENVIRONMENT: ${{ inputs.environment }}
#       FASTLANE_APPSTORE_CONNECT_API_KEY: ${{ secrets.FASTLANE_APPSTORE_CONNECT_API_KEY }}
#       UNITY_ACCOUNT_LOGIN: ${{ secrets.UNITY_ACCOUNT_LOGIN }}
#       UNITY_ACCOUNT_PASSWORD: ${{ secrets.UNITY_ACCOUNT_PASSWORD }}
#       UNITY_ACCOUNT_SERIAL: ${{ secrets.UNITY_ACCOUNT_SERIAL }}
#       UNITY_UPMCONFIG_TOML: ${{ secrets.UNITY_UPMCONFIG_TOML }}
#       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       JIRA_LOGIN: ${{ secrets.JIRA_LOGIN }}
#       JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - name: Bundle install
#         run: bundle install

#       - name: Load ci.json
#         id: json_var
#         run: |
#           content=`cat ./fastlane/ci.json`
#           content="${content//$'\n'/ }"
#           echo "::set-output name=json::$content"

#       - name: Bump build number
#         run: bundle exec fastlane bump_build_number platform:${{env.PLATFORM_TO_BUILD}}

#       - name: Custom build build number
#         run: bundle exec ruby ./fastlane/set_build_number.rb ${{env.PLATFORM_TO_BUILD}} ${{github.event.inputs.build_number}}

#       - name: Custom build build version
#         run: bundle exec ruby ./fastlane/set_version.rb ${{github.event.inputs.build_version}}

#       - name: Select server environment
#         run: bundle exec ruby ./fastlane/select_fortune_server_env.rb ${{env.GAME_SERVER_ENVIRONMENT}}

#       - name: Set OneSignal AppId
#         run: bundle exec ruby ./fastlane/set_one_signal_appid.rb ${{env.GAME_SERVER_ENVIRONMENT}}

#       - name: Unity Touch
#         run: ./fastlane/unity_helper -buildTarget ${{env.PLATFORM_TO_BUILD}} -executeMethod TripleDot.Fortune.Build.AutoBuilder.Touch

#       - name: Unity Build
#         run: ./fastlane/unity_helper -buildTarget ${{env.PLATFORM_TO_BUILD}} -executeMethod TripleDot.Fortune.Build.AutoBuilder.Perform${{env.PLATFORM_TO_BUILD}}Build

#       - name: Copy fastlane files
#         run: |
#           mkdir -p Builds/${{env.PLATFORM_TO_BUILD}}/fastlane
#           cp fastlane/Fastfile Builds/${{env.PLATFORM_TO_BUILD}}/fastlane/Fastfile
#           cp fastlane/Appfile  Builds/${{env.PLATFORM_TO_BUILD}}/fastlane/Appfile
#           cp fastlane/ci.json  Builds/${{env.PLATFORM_TO_BUILD}}/fastlane/ci.json

#       - name: Xcode Build
#         run: cd Builds/${{env.PLATFORM_TO_BUILD}} && bundle exec fastlane build

#       - name: Upload debug symbols to s3
#         run: AWS_DEFAULT_REGION=eu-central-1 bundle exec ruby ./fastlane/upload_symbols_to_s3.rb ${{env.PLATFORM_TO_BUILD}}

#       - name: Upload to AppStoreConnect
#         run: cd Builds/${{env.PLATFORM_TO_BUILD}} && bundle exec fastlane upload

#       - name: Cleanup archives folder
#         run: rm -rf ~/Library/Developer/Xcode/Archives

#       - name: Git commit
#         run: bundle exec ruby ./fastlane/make_git_commit.rb ${{env.PLATFORM_TO_BUILD}}

#       - name: Slack notification
#         run: bundle exec ruby ./fastlane/slack_build_message.rb ${{ env.PLATFORM_TO_BUILD }}
        
#       - name: JIRA automation
#         run: bundle exec ruby ./fastlane/jira_automation.rb ${{env.PLATFORM_TO_BUILD}}

#       - name: Slack failure notification
#         if: ${{ failure() }}
#         run: bundle exec ruby ./fastlane/slack_build_failed_message.rb ${{env.PLATFORM_TO_BUILD}} https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
