
name: Say Hello now and then

on:
  schedule:
  - cron: '2 * * * *'

jobs:
  scheduled_greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: manual greet call
        uses: ./.github/workflows/manual
        with:
          name: "scheduler defined name"
